export const LOG_MESSAGES = {
  TERMINAL: {
    PREFIX: "[BROWSER]:",
  },
  FILE: {
    WRITE_SUCCESS: (count, filePath) => `\nLogged ${count} ${count <= 1 ? "entry" : "entries"} to file: ${filePath}\n`,
    WRITE_ERROR: "Error writing to log file:",
  },
};


export const README_CONTENT = `# Debug Logs

This folder is auto-generated by \`nextjs-mobile-dev-console\` package.

## Contents

- Contains all debug logs with timestamps and metadata

## About

These logs are created when you use \`debug.file()\` or \`useDebug()\` hook with file logging enabled.

Each log entry includes:
- **id**: Unique incrementing identifier
- **timestamp**: When the log was created
- **log**: The actual logged data

## Configuration

You can customize the log file path using:
\`\`\`js
import { initDebug } from 'nextjs-mobile-dev-console/config';

initDebug({ 
  logFilePath: 'custom-path/my-logs.json' 
});
\`\`\`

## Ignore in Git

It's recommended to add this folder to your \`.gitignore\`:
\`\`\`
debug-logs/
\`\`\`

---

For more information, visit: [nextjs-mobile-dev-console](https://www.npmjs.com/package/nextjs-mobile-dev-console?activeTab=readme)
`;
